_default:
    @just --list -u

ip:
    ipconfig getifaddr en0

prom:
    docker run --name prometheus \
      -d -p 9091:9090 \
      -v /Users/zhonghaoyuan/IdeaProjects/treasure-box/treasure-box-prometheus/prometheus.yml:/etc/prometheus/prometheus.yml \
      prom/prometheus \
      --web.enable-lifecycle \
      --config.file=/etc/prometheus/prometheus.yml \
      --storage.tsdb.path=/prometheus \
      --web.console.libraries=/usr/share/prometheus/console_libraries \
      --web.console.templates=/usr/share/prometheus/consoles


grafana:
    docker run --name grafana \
      -d -p 3000:3000 \
      grafana/grafana

refresh:
    curl -X POST 'http://localhost:9091/-/reload'