global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - scheme: http
    timeout: 10s
    api_version: v1
    static_configs:
    - targets: []
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: demo
  scrape_interval: 1s
  scrape_timeout: 1s
  metrics_path: /
  scheme: http
  static_configs:
    - targets:
        - 192.28.1.121:8080
#remote_write:
#  - url: https://cortex-distributor.fusionskye.work/api/prom/push
